version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: UniChat_db
    environment:
      POSTGRES_USER: Unichat
      POSTGRES_PASSWORD: Unichat1234!
      POSTGRES_DB: Unichat-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: