version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: UniChat
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "UniChatAdmin01!"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
